### ISSUE TITLE
Doesn't build on Mavericks

### ISSUE THREAD

**Issue by dpo** [victor/whereami#17]
The Homebrew formula for `whereami` restricts it to Yosemite, but the README suggests it should build on Mavericks. I'm getting the following build errors: https://gist.github.com/902ad744b55f4728e47d
(I know absolutely nothing about Swift.)

Thanks.

**Comment by victor** [comment]
This issue is related to the Swift version you're building with. Which Xcode are you using?
In the future, my intention is to only support the latest Swift (currently, Swift 2). I'm not there yet, the transition to Swift 1.2 and then 2 happened too quick, and I am depending on another library to be updated. So, it will take a while.
Right now the latest Xcode beta doesn't even run on Mavericks, but compiled code should.

**Comment by victor** [comment]
Since now Swift 2 is required, Mavericks is no longer supported
