### ISSUE TITLE
installation/contributors

### ISSUE THREAD

**Issue by wfalkwallace** [victor/whereami#7]
Could you post an installation/compile guide or a CONTRIBUTORS file? I'm getting a "missing library -Lpods" error when I try to build in xcode -- I've tried building pods and whereami both, but I can't seem to get it. Is there a flag I need to set for lib locations? I'm using Xcode defaults.

**Comment by victor** [comment]
I'll add the installation instructions to the README, I don't feel they belong in the CONTRIBUTING file per se.
I am considering also including the pods into the repo itself, so that others don't need to have Cocoapods installed, and can hit the ground running since everything is included. We use that at work at works pretty well, any arguments against?

**Comment by wfalkwallace** [comment]
Well, the cocoapods and .xcworkspace dependencies/installation are really pretty geared toward contributing, not installation/end usage, was my thinking. I just realized I was trying to get it to work and it took me a while to figure out I needed cocoapods and how to do that - I thought it was worth mentioning in your repo.
Including cocoapods sounds like the right plan though, either as a submodule or directly.
Maybe worth also including a githook for wrapping up the binary and providing that for download.
